# config/actions.yaml
action_names:
  0: "stop"
  1: "w"
  2: "s"
  3: "a"
  4: "d"
  5: "attack"
  6: "heavy"
  7: "dodge-forward"
  8: "running_attack"
  9: "heal"
  10: "warp_to_bonfire"

key_bindings:
  w: "w"
  a: "a"
  s: "s"
  d: "d"
  attack: "left"
  heavy_attack: "right"
  dodge: "space"
  jump: "space"
  heal: "q"
  magic: "f"
  weapon_art: "shift"
  crouch: "c"
