# Core Elden Ring addresses (trimmed from SoulsGym example)
# Copy to config/addresses.yaml and verify for your game version.

bases_by_pattern:
  GameDataMan:
    {
      pattern: "\\x48\\x8B\\x05....\\x48\\x85\\xC0\\x74\\x05\\x48\\x8B\\x40\\x58\\xC3\\xC3",
    }
  WorldChrMan:
    { pattern: "\\x48\\x8B\\x05....\\x48\\x85\\xC0\\x74\\x0F\\x48\\x39\\x88" }
  GameMan:
    { pattern: "\\x48\\x8B\\x05....\\x80\\xB8....\\x0D\\x0F\\x94\\xC0\\xC3" }
  FieldArea:
    {
      pattern: "\\x48\\x8B\\x3D....\\x49\\x8B\\xD8\\x48\\x8B\\xF2\\x4C\\x8B\\xF1\\x48\\x85\\xFF",
    }
  LockTgtMan: { pattern: "\\x48\\x8B\\x0D....\\x0F\\x57\\xD2\\xF3\\x0F\\x10." }

addresses:
  PlayerHP:
    { base: WorldChrMan, offsets: [0x10EF8, 0x0, 0x190, 0x0, 0x138], type: int }
  PlayerMaxHP:
    { base: WorldChrMan, offsets: [0x10EF8, 0x0, 0x190, 0x0, 0x13C], type: int }
  PlayerSP:
    { base: WorldChrMan, offsets: [0x10EF8, 0x0, 0x190, 0x0, 0x154], type: int }
  PlayerMaxSP:
    { base: WorldChrMan, offsets: [0x10EF8, 0x0, 0x190, 0x0, 0x158], type: int }
  PlayerMP:
    { base: WorldChrMan, offsets: [0x10EF8, 0x0, 0x190, 0x0, 0x148], type: int }
  PlayerMaxMP:
    { base: WorldChrMan, offsets: [0x10EF8, 0x0, 0x190, 0x0, 0x150], type: int }
  PlayerXYZA:
    {
      base: WorldChrMan,
      offsets: [0x10EF8, 0x0, 0x6C0],
      type: bytes,
      length: 16,
    }
  PlayerLocalXYZ:
    {
      base: WorldChrMan,
      offsets: [0x10EF8, 0x0, 0x190, 0x68, 0x70],
      type: bytes,
      length: 12,
    }
  PlayerAnimation:
    { base: WorldChrMan, offsets: [0x10EF8, 0x0, 0x190, 0x18, 0x20], type: int }
  PlayerGravity:
    {
      base: WorldChrMan,
      offsets: [0x10EF8, 0x0, 0x190, 0x68, 0x1D3],
      type: int,
    }
  AllowPlayerDeath:
    { base: WorldChrMan, offsets: [0x10EF8, 0x0, 0x190, 0x0, 0x19B], type: int }
  LastGrace: { base: GameMan, offsets: [0xB30], type: int }
  Time: { base: GameDataMan, offsets: [0xA0], type: int }
  LocalCam:
    { base: FieldArea, offsets: [0x20, 0x18, 0x30], type: bytes, length: 28 }
  ChunkCamXYZ:
    { base: FieldArea, offsets: [0x20, 0xD0, 0x40], type: bytes, length: 12 }
  PlayerStats: { base: GameDataMan, offsets: [0x08, 0x3C], type: int }
  LockOn: { base: LockTgtMan, offsets: [0x2831], type: bytes, length: 1 }
