ENV_MODE: HYBRID
PROCESS_NAME: eldenring.exe
PYTESSERACT_PATH: C:/msys64/mingw64/bin/tesseract.exe
MONITOR: 1
DEBUG_MODE: false
GAME_MODE: PVE
BOSS: 8
BOSS_HAS_SECOND_PHASE: false
DESIRED_FPS: 24
SIMULATE_MEMORY: false
DISABLE_INPUT: false
LOG_MEMORY_DEBUG: false
MEMORY_DEBUG_INTERVAL: 1
