# Arena metadata (per boss)

process_name: eldenring.exe

arenas:
  - id: 8
    name: Beastman
    nearest_bonfire_key: 'Limgrave - Groveside Cave'
    player_spawn:
      x: 3613.1267
      y: 89.6725
      z: 6971.6821
    player_spawn_angle:
      cos_z: 1.0
      sin_z: 0.0
    boss:
      char_param_id: 39701910:Azula Beastman